model:
  name: pytorch
  build_params:
    num_units: 256
    dropout: 0.5
    num_layers: 2
    device: cpu
    batch_size: 5000
    num_epochs: 50
    scale_data: True
  network:
    num_units: 256
    p_dropout: 0.5
    n_layers: 2
  trainer:
    device: cpu
    batch_size: 5000
    num_epochs: 50
  saver:
    filename: models/torch_model
  sweep:
    run: False
    search_algorithm: bayesian
    split_strategy: timeseries
    num_trials: 50
    scoring_func: r2
    results_csv_path: torch/search_results.csv
    early_stopping: False
    params:
      lr: [0.01, 0.02]
      module__num_units: [10, 50]