model:
  name: pytorch
  build_params:
    num_units: 50
    dropout: 0.5
    num_layers: 10
    device: cpu
    batch_size: 128
    num_epochs: 10
    scale_data: True
  network:
    num_units: 50
    p_dropout: 0.5
    n_layers: 10
  trainer:
    device: cpu
    batch_size: 128
    num_epochs: 10
  saver:
    filename: models/torch_model
  sweep:
    run: True
    search_algorithm: random
    num_trials: 3
    scoring_func: r2
    params:
      lr: [0.01, 0.02]
      module__num_units: [10, 50]